-- Populate learning_videos table in freedb_career_guidence database
USE freedb_career_guidence;

-- Insert video data for all skills
INSERT INTO learning_videos (skill_name, video_title, video_description, youtube_video_id, duration_minutes) VALUES
-- Programming Languages
('Python', 'Python Complete Tutorial', 'Master Python from basics to advanced concepts', '_uQrJ0TkZlc', 280),
('Java', 'Java Full Course', 'Complete Java programming tutorial', 'eIrMbAQSU34', 200),
('JavaScript', 'JavaScript Tutorial', 'Learn JavaScript fundamentals and advanced topics', 'PkZNo7MFNFg', 195),
('C#', 'C# Full Course', 'Complete C# programming guide', 'GhQdlIFylQ8', 244),
('C++', 'C++ Complete Tutorial', 'Learn C++ programming from scratch', 'vLnPwxZdW4Y', 240),
('PHP', 'PHP Tutorial', 'PHP web development complete course', 'OK_JCtrrv-c', 210),
('Ruby', 'Ruby Programming', 'Learn Ruby programming language', 't_ispmWmdjY', 240),
('Go', 'Go Programming Tutorial', 'Complete Go (Golang) course', 'YS4e4q9oBaU', 420),
('Swift', 'Swift Tutorial', 'iOS development with Swift', 'CwA1VWP0Ldw', 180),
('Kotlin', 'Kotlin Full Course', 'Android development with Kotlin', 'F9UC9DY-vIU', 240),
('Dart', 'Dart Programming', 'Learn Dart for Flutter development', '5xlVP04905w', 120),

-- Web Development
('HTML', 'HTML Full Course', 'HTML fundamentals and best practices', 'qz0aGYrrlhU', 120),
('CSS', 'CSS Complete Guide', 'Master CSS styling and layouts', 'yfoY53QXEnI', 180),
('React', 'React Tutorial', 'Build modern web apps with React', 'bMknfKXIFA8', 144),
('Angular', 'Angular Full Course', 'Complete Angular framework guide', 'k5E2AVpwsko', 240),
('Vue.js', 'Vue.js Tutorial', 'Learn Vue.js framework', 'FXpIoQ_rT_c', 180),
('TypeScript', 'TypeScript Course', 'TypeScript for JavaScript developers', 'd56mG7DezGs', 180),
('Node.js', 'Node.js Tutorial', 'Backend development with Node.js', 'TlB_eWDSMt4', 180),

-- Mobile Development
('Flutter', 'Flutter Complete Course', 'Build mobile apps with Flutter', 'VPvVD8t02U8', 240),
('React Native', 'React Native Tutorial', 'Cross-platform mobile development', '0-S5a0eXPoc', 240),
('Android SDK', 'Android Development', 'Native Android app development', 'fis26HvvDII', 300),
('iOS SDK', 'iOS Development', 'Native iOS app development', '09TeUXjzpKs', 240),

-- Databases
('SQL', 'SQL Complete Tutorial', 'Master SQL database queries', 'HXV3zeQKqGY', 240),
('MySQL', 'MySQL Tutorial', 'Learn MySQL database management', '7S_tz1z_5bA', 180),
('PostgreSQL', 'PostgreSQL Course', 'Advanced PostgreSQL database', 'qw--VYLpxG4', 240),
('MongoDB', 'MongoDB Tutorial', 'NoSQL database with MongoDB', 'c2M-rlkkT5o', 180),
('Redis', 'Redis Tutorial', 'In-memory data structure store', 'jgpVdJB2sKQ', 120),

-- Frameworks
('Django', 'Django Tutorial', 'Python web framework', 'rHux0gMZ3Eg', 90),
('Spring Boot', 'Spring Boot Course', 'Java Spring Boot framework', '9SGDpanrc8U', 240),
('ASP.NET', 'ASP.NET Tutorial', '.NET web development', 'BfEjDD8mWYg', 300),
('Laravel', 'Laravel Course', 'PHP Laravel framework', 'ImtZ5yENzgE', 240),
('.NET Core', '.NET Core Tutorial', 'Modern .NET development', 'BfEjDD8mWYg', 300),
('Express.js', 'Express.js Tutorial', 'Node.js web framework', 'L72fhGm1tfE', 120),

-- DevOps & Cloud
('Docker', 'Docker Tutorial', 'Containerization with Docker', 'fqMOX6JJhGo', 180),
('Kubernetes', 'Kubernetes Course', 'Container orchestration', 'X48VuDVv0do', 240),
('AWS', 'AWS Complete Guide', 'Amazon Web Services tutorial', 'SOTamWNgDKc', 600),
('Azure', 'Microsoft Azure Tutorial', 'Cloud computing with Azure', 'NKEFWyqJ5XA', 180),
('Google Cloud', 'Google Cloud Platform', 'GCP fundamentals', 'JPno2xvtGz8', 240),
('CI/CD', 'CI/CD Pipeline Tutorial', 'Continuous Integration & Deployment', 'scEDHsr3APg', 120),
('Git', 'Git Tutorial', 'Version control with Git', 'RGOj5yH7evk', 90),
('Linux', 'Linux Complete Course', 'Linux operating system', 'sWbUDq4S6Y8', 300),
('Jenkins', 'Jenkins Tutorial', 'Automation server', '89yWXXIOisk', 150),
('Terraform', 'Terraform Course', 'Infrastructure as Code', 'l5k1ai_GBDE', 180),

-- Data Science & AI
('Machine Learning', 'Machine Learning Course', 'ML fundamentals and algorithms', 'i_LwzRVP7bg', 480),
('Deep Learning', 'Deep Learning Tutorial', 'Neural networks and deep learning', 'VyWAvY2CF9c', 360),
('Data Analysis', 'Data Analysis Course', 'Analyze data with Python', 'r-uOLxNrNk8', 240),
('Pandas', 'Pandas Tutorial', 'Data manipulation with Pandas', 'vmEHCJofslg', 120),
('NumPy', 'NumPy Course', 'Numerical computing with NumPy', 'QUT1VHiLmmI', 120),
('TensorFlow', 'TensorFlow Tutorial', 'Deep learning framework', 'tPYj3fFJGjk', 240),
('PyTorch', 'PyTorch Course', 'Deep learning with PyTorch', 'c36lUUr864M', 180),
('Scikit-learn', 'Scikit-learn Tutorial', 'Machine learning library', 'pqNCD_5r0IU', 180),
('Data Visualization', 'Data Visualization', 'Visualize data effectively', 'eazGMRuFq78', 150),
('Big Data', 'Big Data Tutorial', 'Big data processing', 'KCEPt0XXAUQ', 240),

-- Design & UX
('Figma', 'Figma Tutorial', 'UI/UX design with Figma', 'FTFaQWZBqQ8', 120),
('UI/UX', 'UI/UX Design Course', 'User interface and experience design', 'c9Wg6Cb_YlU', 180),
('UX Design', 'UX Design Fundamentals', 'User experience design principles', 'c9Wg6Cb_YlU', 180),
('UI Design', 'UI Design Tutorial', 'User interface design best practices', 'c9Wg6Cb_YlU', 180),
('Adobe XD', 'Adobe XD Tutorial', 'Design and prototype with XD', 'WEljsc2jorI', 120),
('Prototyping', 'Prototyping Tutorial', 'Create interactive prototypes', 'FTFaQWZBqQ8', 90),
('Wireframing', 'Wireframing Guide', 'Design effective wireframes', 'FTFaQWZBqQ8', 90),
('User Research', 'User Research Methods', 'Conduct user research', 'c9Wg6Cb_YlU', 120),

-- Testing & Quality
('Testing', 'Software Testing Course', 'Testing methodologies and practices', '_2Dxqf-Cf4k', 180),
('Selenium', 'Selenium Tutorial', 'Test automation with Selenium', 'Uy1hQ1U3S_U', 150),
('Jest', 'Jest Testing Tutorial', 'JavaScript testing framework', 'FgnxcUQ5vho', 90),
('Unit Testing', 'Unit Testing Guide', 'Write effective unit tests', 'ur_xYT_YQBU', 120),
('Test Automation', 'Test Automation Course', 'Automate testing processes', 'Uy1hQ1U3S_U', 180),
('Manual Testing', 'Manual Testing Guide', 'Manual testing techniques', '_2Dxqf-Cf4k', 120),
('Bug Tracking', 'Bug Tracking Systems', 'Track and manage bugs', '_2Dxqf-Cf4k', 60),
('API Testing', 'API Testing Tutorial', 'Test REST APIs effectively', 'lsMQRaeKNDk', 90),

-- Cybersecurity
('Cybersecurity', 'Cybersecurity Course', 'Security fundamentals', 'hXSFdwIOfnE', 300),
('Penetration Testing', 'Penetration Testing', 'Ethical hacking and pen testing', 'WnN6dbos5u8', 240),
('Network Security', 'Network Security', 'Secure network infrastructure', 'qM4S_XKEo8I', 180),
('Ethical Hacking', 'Ethical Hacking Course', 'Learn ethical hacking', 'WnN6dbos5u8', 240),
('Security Tools', 'Security Tools Guide', 'Essential security tools', 'hXSFdwIOfnE', 150),
('Risk Assessment', 'Risk Assessment Methods', 'Assess security risks', 'hXSFdwIOfnE', 90),
('Incident Response', 'Incident Response', 'Handle security incidents', 'hXSFdwIOfnE', 120),

-- Other Technologies
('Blockchain', 'Blockchain Tutorial', 'Blockchain technology fundamentals', 'qOVAbKKSH10', 240),
('GraphQL', 'GraphQL Course', 'API development with GraphQL', 'ed8SzALpx1Q', 120),
('REST API', 'REST API Tutorial', 'Build RESTful web services', 'lsMQRaeKNDk', 90),
('REST APIs', 'REST APIs Guide', 'RESTful API best practices', 'lsMQRaeKNDk', 90),
('Microservices', 'Microservices Architecture', 'Design microservices systems', 'CdBtNQZH8a4', 180),
('OAuth', 'OAuth 2.0 Tutorial', 'Authentication and authorization', '996OiexHze0', 90),
('WebSockets', 'WebSockets Tutorial', 'Real-time communication', 'i5OVcTdt_OU', 60),
('Agile', 'Agile Methodology', 'Agile software development', 'Z9QbYZh1YXY', 90),
('Scrum', 'Scrum Framework', 'Scrum agile framework', 'XU0llRltyFM', 60),
('API Development', 'API Development Guide', 'Build robust APIs', 'lsMQRaeKNDk', 120),
('Cloud Computing', 'Cloud Computing Fundamentals', 'Introduction to cloud services', 'M988_fsOSWo', 180),
('Data Structures', 'Data Structures Tutorial', 'Essential data structures', 'RBSGKlAvoiM', 240),
('Algorithms', 'Algorithms Course', 'Algorithm design and analysis', 'pLT_9jwaPzs', 300),
('System Design', 'System Design Interview', 'Design scalable systems', 'MbjObHmDbZo', 180),
('Software Architecture', 'Software Architecture', 'Architectural patterns and practices', '5yF4EH1Rlg8', 240),
('OOP', 'Object-Oriented Programming', 'OOP principles and patterns', 'pTB0EiLXUC8', 180),
('Design Patterns', 'Design Patterns Tutorial', 'Software design patterns', 'NU_1StN5Tkk', 180),
('Leadership', 'Leadership Skills', 'Develop leadership abilities', 'VU3a5URrH8Y', 120),
('Communication', 'Communication Skills', 'Effective communication', 'xcSml7J6pDg', 90),
('Documentation', 'Technical Documentation', 'Write great documentation', 'kFZ8e6dM_Xk', 90),
('Roadmapping', 'Product Roadmapping', 'Create product roadmaps', 'XU0llRltyFM', 90),
('Product Strategy', 'Product Strategy Guide', 'Define product strategy', 'XU0llRltyFM', 120),
('Requirements Gathering', 'Requirements Gathering', 'Gather business requirements', 'Z9QbYZh1YXY', 90),
('Process Modeling', 'Process Modeling', 'Model business processes', 'Z9QbYZh1YXY', 90),
('Networking', 'Computer Networking', 'Network fundamentals', 'qiQR5rTSshw', 300),
('IoT', 'Internet of Things', 'IoT development basics', 'LlhmzVL5bm8', 180),
('Embedded Systems', 'Embedded Systems', 'Embedded programming', 'Qo5dUdBE4qk', 240),
('Sensors', 'Sensor Technology', 'Working with sensors', 'LlhmzVL5bm8', 120),
('Cloud Integration', 'Cloud Integration', 'Integrate with cloud services', 'M988_fsOSWo', 150),
('AR/VR', 'AR/VR Development', 'Augmented and Virtual Reality', 'p1FV5aXS-HE', 240),
('Computer Vision', 'Computer Vision', 'Computer vision fundamentals', 'VyWAvY2CF9c', 180),
('Mobile Development', 'Mobile Development', 'Mobile app development', 'VPvVD8t02U8', 240),
('UI/UX Design', 'UI/UX Design Complete', 'Complete UI/UX guide', 'c9Wg6Cb_YlU', 240),
('State Management', 'State Management', 'Manage application state', 'bMknfKXIFA8', 90),
('Firebase', 'Firebase Tutorial', 'Backend services with Firebase', 'fgdpvwEWJ9M', 180),
('Responsive Design', 'Responsive Design', 'Build responsive websites', 'yfoY53QXEnI', 120),
('Performance Tuning', 'Performance Optimization', 'Optimize application performance', 'bMknfKXIFA8', 120),
('Backup & Recovery', 'Backup & Recovery', 'Database backup strategies', '7S_tz1z_5bA', 90),
('Database Design', 'Database Design', 'Design effective databases', 'HXV3zeQKqGY', 150),
('Security', 'Security Best Practices', 'Security fundamentals', 'hXSFdwIOfnE', 180),
('Monitoring', 'System Monitoring', 'Monitor applications and infrastructure', 'X48VuDVv0do', 120),
('Cryptography', 'Cryptography Basics', 'Encryption and security', 'qOVAbKKSH10', 150),
('Web3', 'Web3 Development', 'Decentralized web development', 'qOVAbKKSH10', 180),
('Solidity', 'Solidity Programming', 'Smart contract development', 'qOVAbKKSH10', 180),
('Smart Contracts', 'Smart Contracts', 'Write smart contracts', 'qOVAbKKSH10', 150),
('Ethereum', 'Ethereum Development', 'Build on Ethereum', 'qOVAbKKSH10', 180),
('Unity', 'Unity Game Development', 'Create games with Unity', '9pF3TsTJ-IQ', 300),
('Unreal Engine', 'Unreal Engine Tutorial', 'Game development with Unreal', 'gQmiqmxJMtA', 360),
('3D Graphics', '3D Graphics Programming', '3D graphics fundamentals', 'gQmiqmxJMtA', 240),
('Game Design', 'Game Design Principles', 'Design engaging games', '9pF3TsTJ-IQ', 180),
('Physics', 'Physics for Games', 'Game physics programming', '9pF3TsTJ-IQ', 120),
('NLP', 'Natural Language Processing', 'NLP with Python', 'fM4qTMfCoak', 240),
('Neural Networks', 'Neural Networks', 'Deep neural networks', 'VyWAvY2CF9c', 240),
('Cloud Architecture', 'Cloud Architecture', 'Design cloud solutions', 'SOTamWNgDKc', 240),
('Statistics', 'Statistics for Data Science', 'Statistical analysis', 'xxpc-HPKN28', 240),
('R', 'R Programming', 'Data analysis with R', '_V8eKsto3Ug', 180);

-- Show count
SELECT COUNT(*) as total_videos FROM learning_videos;
